# Generated by Django 5.1.3 on 2024-11-08 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_phrase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='author',
            field=models.CharField(default='Autor Desconhecido', max_length=255),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.category'),
        ),
    ]
