INSERT INTO dashboard_phrase (author, content, created_at, category_id) VALUES
    ('Desconhecido', 'A tristeza é um convite para olhares para dentro e encontrares a tua própria luz.', NOW(), 1),
    ('Helen Keller', 'Embora o mundo esteja cheio de sofrimento, ele também está cheio de superação.', NOW(), 1),
    ('Confúcio', 'Nossa maior glória não está em nunca cair, mas em nos levantarmos toda vez que caímos.', NOW(), 1),
    ('Desconhecido', 'A tristeza não te define, é apenas uma parte do teu caminho.', NOW(), 1),
    ('Desconhecido', 'Tudo passa, inclusive as fases tristes. Acredita no amanhã.', NOW(), 1),
    ('Desconhecido', 'Lembra-te que o descanso é parte do progresso.', NOW(), 2),
    ('Albert Einstein', 'Nem tudo que conta pode ser contado, e nem tudo que pode ser contado conta.', NOW(), 2),
    ('Desconhecido', 'Respira. Tudo o que é urgente se resolverá com calma e clareza.', NOW(), 2),
    ('Winston Churchill', 'O sucesso não é final, o fracasso não é fatal: o que conta é a coragem de continuar.', NOW(), 2),
    ('Desconhecido', 'Trabalha com foco, mas não te esqueças de cuidar de ti.', NOW(), 2),
    ('Desconhecido', 'Perdoa-te pelos erros do passado e segue em frente.', NOW(), 3),
    ('Desconhecido', 'A culpa é um fardo pesado; liberta-te dela para voares mais alto.', NOW(), 3),
    ('Oprah Winfrey', 'Perdoa-te pelo que achas que fez de errado, e lembra-te do teu valor.', NOW(), 3),
    ('Desconhecido', 'Cada erro é uma lição. Foca-te no que podes aprender.', NOW(), 3),
    ('Buda', 'Você mesmo, tanto quanto qualquer outra pessoa em todo o universo, merece o seu amor e carinho.', NOW(), 3),
    ('Desconhecido', 'O teu corpo é o lar da tua alma. Trata-o com amor.', NOW(), 4),
    ('Desconhecido', 'A beleza começa no momento em que decides ser tu mesmo.', NOW(), 4),
    ('Ralph Waldo Emerson', 'Para ser insubstituível, devemos ser diferentes.', NOW(), 4),
    ('Desconhecido', 'Tu és mais do que a tua aparência. A tua essência é o que brilha.', NOW(), 4),
    ('Desconhecido', 'Cada corpo é único e merece respeito e amor.', NOW(), 4),
    ('Desconhecido', 'Não tens de ser perfeito para seres aceito.', NOW(), 5),
    ('Desconhecido', 'Lembra-te que muitos têm as mesmas inseguranças. És compreendido.', NOW(), 5),
    ('Maya Angelou', 'Aprendi que as pessoas esquecerão o que você disse, mas nunca esquecerão como você as fez sentir.', NOW(), 5),
    ('Desconhecido', 'A ansiedade é passageira. Respira fundo e vai devagar.', NOW(), 5),
    ('Desconhecido', 'A tua presença é valiosa. Lembra-te disso sempre.', NOW(), 5),
    ('Desconhecido', 'A tua companhia é mais do que suficiente. Confia no teu próprio valor.', NOW(), 6),
    ('Helen Keller', 'Sozinhos, podemos fazer tão pouco; juntos, podemos fazer tanto.', NOW(), 6),
    ('Desconhecido', 'A solidão pode ser o início de um grande autoconhecimento.', NOW(), 6),
    ('Desconhecido', 'Estar sozinho não significa estar perdido. É uma oportunidade para crescer.', NOW(), 6),
    ('Desconhecido', 'A solidão pode ser a chave para uma paz profunda.', NOW(), 6),
    ('Desconhecido', 'Confia em ti mesmo. Tens mais força do que pensas.', NOW(), 7),
    ('Desconhecido', 'A autoconfiança é o primeiro passo para o sucesso.', NOW(), 7),
    ('Desconhecido', 'Lembra-te de quantas vezes superaste os teus próprios limites.', NOW(), 7),
    ('Desconhecido', 'A dúvida é apenas uma sombra. O teu valor é real.', NOW(), 7),
    ('Desconhecido', 'O primeiro passo para o sucesso é acreditar que mereces.', NOW(), 7),
    ('Desconhecido', 'A calma é a chave para venceres a ansiedade.', NOW(), 8),
    ('Desconhecido', 'O momento presente é onde a paz vive. Respira e foca-te no agora.', NOW(), 8),
    ('Desconhecido', 'Tudo o que vem, também passa. Acalma o teu coração.', NOW(), 8),
    ('Desconhecido', 'A ansiedade não define quem és. Respira e recomeça.', NOW(), 8),
    ('Lao Tzu', 'A natureza não se apressa, mas tudo se realiza.', NOW(), 8),
    ('Desconhecido', 'A paz interior é o verdadeiro controle da raiva.', NOW(), 9),
    ('Dalai Lama', 'A paciência é o melhor remédio contra a raiva.', NOW(), 9),
    ('Desconhecido', 'Respira fundo. A serenidade é a força real.', NOW(), 9),
    ('Desconhecido', 'Escolher o silêncio é um ato de coragem.', NOW(), 9),
    ('Desconhecido', 'O controle da raiva começa com o autocontrole.', NOW(), 9),
    ('Desconhecido', 'O primeiro passo é sempre o mais difícil. Dá-o com confiança.', NOW(), 10),
    ('Desconhecido', 'Não esperes pela motivação; começa e a motivação virá.', NOW(), 10),
    ('Desconhecido', 'O segredo do progresso é o começo.', NOW(), 10),
    ('Desconhecido', 'A cada tarefa concluída, uma nova vitória pessoal.', NOW(), 10),
    ('Desconhecido', 'Avançar um pouco a cada dia é melhor que a perfeição adiada.', NOW(), 10),
    ('Desconhecido', 'Confia nas tuas conquistas. Elas são fruto do teu trabalho.', NOW(), 11),
    ('Desconhecido', 'Lembra-te que mereces estar onde estás.', NOW(), 11),
    ('Desconhecido', 'Cada desafio superado é uma prova do teu valor.', NOW(), 11),
    ('Desconhecido', 'A tua autenticidade é o teu maior poder.', NOW(), 11),
    ('Desconhecido', 'O sucesso é para aqueles que ousam acreditar em si mesmos.', NOW(), 11);
